########################################### Consul ###########################################
consul_version: '1.9.1'
consul_dl_url: 'https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip'

########################################### Vault ###########################################
vault_version: '1.6.1'
vault_dl_url: 'https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip'