FROM nginx:1.19.6-alpine

RUN mkdir /etc/nginx/tls
COPY conf/tls/*.crt /etc/nginx/tls/vault.crt
COPY conf/tls/*.key /etc/nginx/tls/vault.key

COPY conf/docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY conf/docker/nginx/nginx_vault.conf /etc/nginx/conf.d/vault.conf