ARGS VAULT_VERSION
FROM vault:${VAULT_VERSION}

# add the config file
COPY conf/docker/vault/vault-config.hcl /vault/config/vault-config.hcl

# run vault
CMD vault server -config=/vault/config/vault-config.hcl