ARG CONSUL_VERSION
FROM consul:${CONSUL_VERSION}

# add the config file
COPY conf/docker/consul/consul-config.hcl /consul/config/consul-config.hcl

# run consul
CMD consul agent -config-file=/consul/config/consul-config.hcl